charts: 
- yKey: train/episode/rew_total/mean
  xKey: iterations
- yKey: train/episode/rew_tracking_lin_vel/mean
  xKey: iterations
- yKey: train/episode/rew_tracking_contacts_shaped_force/mean
  xKey: iterations
- yKey: train/episode/rew_tracking_contacts_shaped_force_scaled/mean
  xKey: iterations
- yKey: train/episode/rew_ang_vel_xy/mean
  xKey: iterations
- yKey: train/episode/rew_dof_acc/mean
  xKey: iterations
- yKey: train/episode/rew_collision/mean
  xKey: iterations
- yKey: train/episode/rew_action_rate/mean
  xKey: iterations
- yKey: train/episode/rew_torques/mean
  xKey: iterations
- yKey: train/episode/rew_dof_pos_limits/mean
  xKey: iterations
- yKey: train/episode/rew_feet_clearance_cmd_linear/mean
  xKey: iterations
- yKey: train/episode/rew_feet_accel/mean
  xKey: iterations
- yKey: train/episode/rew_tracking_contacts_shaped_vel/mean
  xKey: iterations
- yKey: train/episode/rew_raibert_heuristic/mean
  xKey: iterations
- yKey: train/episode/rew_estimation_bonus/mean
  xKey: iterations
- yKey: train/episode/terrain_level/mean
  xKey: iterations
- type: video
  glob: "videos/*.mp4"
- yKey: adaptation_loss/mean
  xKey: iterations
- yKey: friction_loss/mean
  xKey: iterations
- yKey: roughness_loss/mean
  xKey: iterations
- yKey: stair_height/mean
  xKey: iterations
- yKey: stair_run/mean
  xKey: iterations
- yKey: stair_ori/mean
  xKey: iterations
- yKey: motion_loss/mean
  xKey: iterations

