"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class realsense_lcmt(object):
    __slots__ = ["commands"]

    def __init__(self):
        self.commands = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(realsense_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.commands[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != realsense_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return realsense_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = realsense_lcmt()
        self.commands = struct.unpack('>4f', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if realsense_lcmt in parents: return 0
        tmphash = (0x476d343daaf897a9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if realsense_lcmt._packed_fingerprint is None:
            realsense_lcmt._packed_fingerprint = struct.pack(">Q", realsense_lcmt._get_hash_recursive([]))
        return realsense_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

